# Configuraci칩n del plugin MangoUHC
uhc:
    # Radio en bloques para el borde donde se colocar치n los jugadores al inicio
    border-radius: 1000

    # Configuraci칩n del world border
    world-border:
        size: 1500

    # Configuraci칩n de scatter
    scatter:
        max-attempts: 50
