name: MangoUHC
version: "${version}"
main: com.spectrasonic.MangoUHC.Main
api-version: "1.21"
authors: [Spectrasonic]
depends: [FastAsyncWorldEdit]

commands:
    mango:
        permission: mangouhc.mango
    timer:
        permission: timer.use
    pvp:
        permission: mangouhc.command.pvp
    cage:
        permission: mangouhc.cage

permissions:
    mangouhc.mango:
        default: true
    mangouhc.command.pvp:
        default: op
    mangouhc.command.uhc:
        default: op
    mangouhc.command.uhc.reload:
        default: op
    mangouhc.cage:
        default: op
    mangouhc.timer.*:
        children:
            mangouhc.timer.create:
                default: op
            mangouhc.timer.add:
                default: op
            mangouhc.timer.pause:
                default: op
            mangouhc.timer.stop:
                default: op
            mangouhc.timer.list:
                default: op
            mangouhc.timer.stopall:
                default: op
