name: MangoUHC
version: "${version}"
main: com.spectrasonic.MangoUHC.Main
api-version: "1.21"
authors: [Spectrasonic]
commands:
    mango:
        permission: mangouhc.mango
    timer:
        permission: timer.use

permissions:
    mangouhc.mango:
        default: true
    mangouhc.timer.*:
        children:
            mangouhc.timer.create:
                default: op
            mangouhc.timer.add:
                default: op
            mangouhc.timer.pause:
                default: op
            mangouhc.timer.stop:
                default: op
            mangouhc.timer.list:
                default: op
            mangouhc.timer.stopall:
                default: op
